name: Alex App Version Action
on:
  # Trigger the workflow on push request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  Version-check:
    runs-on: ubuntu-latest
    name: Increment Tag Version
    steps:
    - name: Increment version
      id: version   
      uses: alxppgithub/pinf-69@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
